name: Tests and code
on: [ push, pull_request ]

jobs:
  testing:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.3', '7.4' ]

    steps:
      - name: Checkout Coder
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, sqlite
          ini-values: max_execution_time=180
          # Disable Xdebug for better performance.
          coverage: none
      - name: Run tests
        run: ./tests/test_run.sh
